#!/usr/bin/env python3
"""framework import — plan adopting an EXISTING (foreign) vault into a pack (okengine#154).

Read-only by default: produces a complete, reviewable CHANGE REPORT (type distribution vs the pack
schema, id-backfill collisions, untyped pages, layout) WITHOUT writing. `--scaffold` writes a
pack-local skeleton migration the author fills in (retype map, field remaps); the actual apply then
rides `framework upgrade <pack> --apply` — reusing #66's snapshot / rollback / validate harness, so
the irreversible id-backfill is survivable. The heavy lifting reuses existing primitives
(backfill_ids, okf_migrate, the normalize suite) via import_lib — this is the assembled PATH, not
new machinery.

Usage:
  framework import <pack-dir> --vault <foreign-vault-dir> [--scaffold]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE / "cron"))
import import_lib  # noqa: E402

SKELETON = '''\
"""Import migration (okengine#154) — adopt a foreign vault into this pack.

Generated by `framework import --scaffold`. FILL THE TWO MAPS, then dry-run with
`framework upgrade <pack>` and apply with `--apply` (snapshot + rollback + validate gate).
Order matters: retype -> field reconcile -> LAYOUT (re-home) -> id backfill -> validate (gate).
"""
from pathlib import Path
import import_lib   # engine helper; `framework upgrade` puts the engine scripts/ dir on sys.path

ID = "import-foreign-vault"
FROM = "0.0.0"
TO = "{to}"           # set to this pack's engine_release so `upgrade` selects it once
DESCRIPTION = "Adopt the foreign vault into this pack's schema"

# 1. type_aliases / deterministic retypes — {{foreign_type: pack_type}}
RETYPE_MAP = {{}}
# 1b. curated/classifier retypes — {{page_slug: pack_type}} (e.g. specific concepts -> segment)
RETYPE_SLUGS = {{}}
# 2. per-type frontmatter reconciliation — {{type: {{"rename": {{old: new}}, "default": {{f: v}}}}}}
FIELD_REMAP = {{}}
# 3. layout overrides — pack types that own a DEDICATED namespace (documents, NOT entity-graph
#    nouns). derive_ns_map() routes every pack `type` to entities/ by default; name the exceptions
#    here, e.g. {{"report": "reports", "question": "questions"}}.
NS_FOR_TYPE = {{}}


def apply(pack: Path, dry_run: bool) -> list:
    import yaml
    wiki = (pack / "wiki") if (pack / "wiki").is_dir() else pack
    changes = []
    changes += import_lib.retype_by_type(wiki, RETYPE_MAP, apply=not dry_run)
    changes += import_lib.set_type_for_slugs(wiki, RETYPE_SLUGS, apply=not dry_run)
    changes += import_lib.remap_fields(wiki, FIELD_REMAP, apply=not dry_run)
    # 4. LAYOUT (okengine#154) — re-home each page to the namespace its TYPE dictates, rewriting
    #    every [[reference]] in lockstep (link-preserving; raises -> snapshot rollback if a ref is
    #    lost). This is the step a raw bulk-copy skips — without it, sources sit under frontier/ etc.
    schema = yaml.safe_load((pack / "schema.yaml").read_text()) if (pack / "schema.yaml").is_file() else {{}}
    ns_for_type = import_lib.derive_ns_map(schema)
    ns_for_type.update(NS_FOR_TYPE)
    changes += import_lib.rehome_by_type(wiki, ns_for_type, apply=not dry_run)
    # 4b. normalize source date-DEPTH: sources/YYYY/MM/DD/slug -> sources/YYYY/MM/slug (foreign vaults
    #     may nest a day-dir; okengine + the index/dedup scans assume exactly two date segments).
    changes += import_lib.collapse_source_dates(wiki, apply=not dry_run)
    # 5. id backfill — IRREVERSIBLE; authority-id duplicates are a human-merge worklist, see the
    #    import report. Uncomment once RETYPE/FIELD/LAYOUT are settled (ids depend on final path):
    #     import backfill_ids; changes.append(str(backfill_ids.run(wiki.parent, apply=not dry_run)))
    # 6. validate is the roll-forward gate `framework upgrade` runs automatically.
    return changes
'''


def _report(pack: Path, vault: Path) -> int:
    sys.path.insert(0, str(_HERE / "cron"))
    import schema_lib
    wiki = (vault / "wiki") if (vault / "wiki").is_dir() else vault
    if not wiki.is_dir():
        print(f"ERROR: no wiki/ under {vault}", file=sys.stderr)
        return 2
    schema = schema_lib.governing_schema(pack)
    pack_types = set((schema.get("types") or {}).keys())
    aliases = set((schema.get("type_aliases") or {}).keys())

    inv = import_lib.scan(wiki)
    print(f"=== import plan: {vault}  ->  pack {pack.name} ===")
    print(f"  pages: {inv['pages']}  (typed {inv['typed']}, untyped {inv['untyped']})")
    print("  type distribution vs pack schema:")
    for t, n in inv["types"].items():
        if t in pack_types:
            tag = "ok"
        elif t in aliases:
            tag = "via type_aliases"
        else:
            tag = "NOT IN PACK -> add a RETYPE_MAP entry or pack type"
        print(f"    {t:24} {n:>7}   [{tag}]")
    if inv["untyped"]:
        print(f"    {'(untyped)':24} {inv['untyped']:>7}   [needs a type — RETYPE_SLUGS / backfill_typeless_type]")

    mis = import_lib.layout_misplaced(wiki, import_lib.derive_ns_map(schema))
    if mis:
        print(f"  LAYOUT — {sum(mis.values())} page(s) in the WRONG namespace for their type "
              f"(the migration's re-home step fixes this, link-preserving):")
        for k, c in list(mis.items())[:10]:
            print(f"    {c:>7}  {k}")
        print("    NOTE: a pack type with a dedicated namespace (e.g. report->reports) needs an "
              "NS_FOR_TYPE override in the migration, else derive_ns_map routes it to entities/.")

    try:
        ids = import_lib.id_collisions(vault)
        print(f"  ids: {ids['stamped']} page(s) would be stamped; "
              f"{len(ids['slug_collisions'])} slug collision(s) (auto-disambiguated); "
              f"{len(ids['authority_collisions'])} AUTHORITY collision(s) -> HUMAN MERGE worklist")
        for cid, a, b in ids["authority_collisions"][:20]:
            print(f"      DUP id {cid}: {a}  vs  {b}")
        if not (pack / "schema.yaml").is_file():
            print("    NOTE: id authority bindings come from the pack schema — rerun after the "
                  "pack schema governs the vault for accurate authority-collision detection.")
    except Exception as e:
        print(f"  ids: (could not compute — {e})")
    print("\n  next: `--scaffold` writes a skeleton migration; fill RETYPE_MAP/FIELD_REMAP, then "
          "`framework upgrade <pack> --apply` (snapshot + rollback + validate).")
    return 0


def _scaffold(pack: Path) -> int:
    sys.path.insert(0, str(_HERE))
    import framework_upgrade
    import engine_meta
    mdir = pack / ".okengine" / "migrations"
    mdir.mkdir(parents=True, exist_ok=True)
    dest = mdir / "m_900_import_foreign_vault.py"
    if dest.exists():
        print(f"  exists (left untouched): {dest}")
        return 0
    to = engine_meta.engine_release() if hasattr(engine_meta, "engine_release") else "0.6.0"
    dest.write_text(SKELETON.format(to=to), encoding="utf-8")
    print(f"  scaffolded: {dest}\n  fill RETYPE_MAP / RETYPE_SLUGS / FIELD_REMAP, then "
          f"`framework upgrade {pack} ` (dry-run) and `--apply`.")
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="framework import")
    ap.add_argument("pack", type=Path, help="target pack directory (has schema.yaml)")
    ap.add_argument("--vault", type=Path, required=True, help="foreign vault to adopt")
    ap.add_argument("--scaffold", action="store_true", help="write a pack-local skeleton migration")
    args = ap.parse_args(argv)
    rc = _report(args.pack, args.vault)
    if rc == 0 and args.scaffold:
        rc = _scaffold(args.pack)
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
