#!/usr/bin/env python3
"""One-time vault maintenance: reconcile duplicate entity canonicals that accumulated under
two sharding schemes (okengine#48).

The engine writes canonicals one-level — `entities/<slug[0]>/<slug>.md`. Legacy/agent writes
created two-level copies — `entities/<slug[0]>/<slug[1]>/<slug>.md`. The assembler only touches
the one-level path, so the two-level copies are stale orphans (yet often hold the richer body),
and the reader can mis-resolve to them. This script collapses every two-level entity page into
its one-level canonical, PRESERVING content, then removes the two-level copy.

Per two-level page (slug S, one-level O = entities/S[0]/S.md):
  - O missing            -> RELOCATE: the two-level page IS the canonical; move it to O.
  - O exists             -> MERGE: union frontmatter (O, the current/assembled page, wins on
                            shared keys; the legacy page fills gaps), keep the richer body
                            (O's if it has real content/agent sections, else the two-level
                            body; unique `## ` sections from the two-level page are appended,
                            never dropped), strip the per-source envelope, write O, remove the
                            two-level page.

Dry-run by default (prints the plan). `--apply` performs it; `--backup-dir DIR` tars the
two-level pages first (default: a sibling backup). Re-run the assembler afterwards.

Usage: okf_dedup_entity_shards.py --vault DIR [--apply] [--backup-dir DIR]
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

import yaml

_FM = re.compile(r"\A---\s*\n(.*?\n)---\s*\n?(.*)\Z", re.S)
_ENVELOPE = {"source", "canonical", "reliability", "credibility"}


def _split(text: str) -> tuple[str, str]:
    m = _FM.match(text)
    return (m.group(1), m.group(2)) if m else ("", text)


def _fm(fm_text: str) -> dict:
    try:
        d = yaml.safe_load(fm_text) if fm_text.strip() else {}
        return d if isinstance(d, dict) else {}
    except yaml.YAMLError:
        return {}


def _norm(body: str) -> str:
    lines = [ln.strip() for ln in body.splitlines()
             if ln.strip() and not ln.lstrip().startswith(">")]
    return re.sub(r"\s+", " ", " ".join(lines)).strip()


def _is_bare(body: str, slug: str) -> bool:
    n = _norm(body).rstrip(".").strip().lower()
    return (not n) or n == slug.replace("-", " ").strip() or len(n) <= len(slug) + 2


def _sections(body: str) -> dict:
    """{'## Header': 'section text'} for each level-2 heading in a body."""
    out, cur, buf = {}, None, []
    for ln in body.splitlines():
        if ln.startswith("## "):
            if cur is not None:
                out[cur] = "\n".join(buf).strip()
            cur, buf = ln.strip(), []
        elif cur is not None:
            buf.append(ln)
    if cur is not None:
        out[cur] = "\n".join(buf).strip()
    return out


def _choose_body(one_body: str, two_body: str, slug: str) -> str:
    """Richer body wins; the two-level page's UNIQUE `## ` sections are appended, never lost."""
    if _is_bare(one_body, slug) and _norm(two_body):
        return two_body
    have = _sections(one_body)
    extra = [f"{h}\n{t}".rstrip() for h, t in _sections(two_body).items() if h not in have]
    return (one_body.rstrip() + "\n\n" + "\n\n".join(extra) + "\n") if extra else one_body


def _merge_fm(one_fm: dict, two_fm: dict) -> dict:
    out = {**two_fm, **one_fm}                  # one-level (assembled/current) wins on shared keys
    for k in _ENVELOPE:
        out.pop(k, None)
    return out


def _render(fm: dict, body: str) -> str:
    head = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True,
                          default_flow_style=None).rstrip("\n")
    return "---\n" + head + "\n---\n" + body.lstrip("\n")


def _is_index(p: Path, fm_text: str) -> bool:
    """Generated navigation pages (INDEX.md / INDEX-pNN.md, type: dashboard) are not entities —
    one per shard dir, regenerated by the index cron. Skip them; the stale ones are pruned."""
    return p.name.startswith("INDEX") or str(_fm(fm_text).get("type") or "") == "dashboard"


def plan(vault: Path) -> dict:
    ent = vault / "wiki" / "entities"
    two = [p for p in ent.rglob("*.md")
           if len(p.relative_to(ent).parts) >= 3 and not p.name.startswith(("_", "."))]
    acts = {"relocate": [], "merge": [], "appended": [], "index": []}
    for p in two:
        slug = p.stem
        tf0, _ = _split(p.read_text(encoding="utf-8", errors="replace"))
        if _is_index(p, tf0):
            acts["index"].append(p)
            continue
        o = ent / slug[0].lower() / f"{slug}.md"
        if not o.exists():
            acts["relocate"].append((p, o))
            continue
        of, ob = _split(o.read_text(encoding="utf-8", errors="replace"))
        tf, tb = _split(p.read_text(encoding="utf-8", errors="replace"))
        merged = _render(_merge_fm(_fm(of), _fm(tf)), _choose_body(ob, tb, slug))
        acts["merge"].append((p, o, merged))
        if not _is_bare(ob, slug) and _sections(tb).keys() - _sections(ob).keys():
            acts["appended"].append(str(p))
    return acts


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Reconcile two-level entity duplicates (okengine#48).")
    ap.add_argument("--vault", required=True)
    ap.add_argument("--apply", action="store_true", help="perform it (default: dry-run)")
    ap.add_argument("--backup-dir", help="tar two-level pages here before removal")
    args = ap.parse_args(argv)
    vault = Path(args.vault)
    acts = plan(vault)
    print(f"two-level entity pages: {len(acts['relocate']) + len(acts['merge'])} "
          f"(+ {len(acts['index'])} stale index/dashboard pages to prune)")
    print(f"  relocate (no one-level twin): {len(acts['relocate'])}")
    print(f"  merge into one-level:         {len(acts['merge'])} "
          f"({len(acts['appended'])} append agent sections from the two-level page)")
    if not args.apply:
        print("dry-run; re-run with --apply to perform. Sample appends:",
              acts["appended"][:5])
        return 0
    if args.backup_dir:
        bdir = Path(args.backup_dir)
        bdir.mkdir(parents=True, exist_ok=True)
        for p, *_ in acts["relocate"] + acts["merge"] + [(x,) for x in acts["index"]]:
            dest = bdir / p.relative_to(vault / "wiki")
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, dest)
        print(f"backed up {len(acts['relocate']) + len(acts['merge']) + len(acts['index'])} "
              f"two-level pages to {bdir}")
    for p, o in acts["relocate"]:
        o.parent.mkdir(parents=True, exist_ok=True)
        o.write_text(p.read_text(encoding="utf-8", errors="replace"), encoding="utf-8")
        p.unlink()
    for p, o, merged in acts["merge"]:
        o.write_text(merged, encoding="utf-8")
        p.unlink()
    for p in acts["index"]:                      # stale two-level index pages; regenerated by cron
        p.unlink()
    # prune now-empty two-level shard dirs
    ent = vault / "wiki" / "entities"
    for d in sorted((d for d in ent.rglob("*") if d.is_dir()), key=lambda x: -len(x.parts)):
        if d != ent and not any(d.iterdir()):
            d.rmdir()
    print(f"applied: {len(acts['relocate'])} relocated, {len(acts['merge'])} merged, "
          f"two-level pages removed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
