#!/usr/bin/env python3
"""Build wiki/dashboards/timeline.md — a reverse-chronological view of the vault's dated content
(okengine.timeline). Deterministic, domain-agnostic: scans sources (`published:`) and
entities/pages (`updated:`/`created:`), groups by month, renders a timeline of [[wikilinks]].
No agent, no network — the established engine dashboard-generator pattern (cf. contradictions)."""
import os
import re
from datetime import date, datetime, timezone
from pathlib import Path

try:
    import yaml
except Exception:                              # pragma: no cover - yaml is a runtime dep
    yaml = None

VAULT = Path(os.environ.get("WIKI_PATH", "/opt/vault"))
WIKI = VAULT / "wiki"
DASH_PATH = WIKI / "dashboards" / "timeline.md"
MAX_ENTRIES = int(os.environ.get(
    "OKENGINE_CONFIG_MAX_ENTRIES", os.environ.get("OKENGINE_TIMELINE_MAX_ENTRIES", "300")
))

_FM = re.compile(r"^---\n(.*?)\n---\n", re.S)
_DATE = re.compile(r"(\d{4})-(\d{2})-(\d{2})")
_SKIP_PREFIXES = ("dashboards/", "operational/")   # derived / ops, not knowledge


def frontmatter(text: str) -> dict:
    m = _FM.match(text)
    if not m or yaml is None:
        return {}
    try:
        d = yaml.safe_load(m.group(1))
        return d if isinstance(d, dict) else {}
    except Exception:
        return {}


def to_date(v):
    if isinstance(v, datetime):       # YAML may parse a timestamp as datetime (date subclass)
        return v.date()
    if isinstance(v, date):
        return v
    m = _DATE.search(str(v or ""))
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    except ValueError:
        return None


def collect(wiki: Path) -> list:
    """[(date, slug, type, title)] for dated knowledge pages, newest first."""
    out = []
    if not wiki.is_dir():
        return out
    for p in wiki.rglob("*.md"):
        rel = p.relative_to(wiki).as_posix()
        if rel.startswith(_SKIP_PREFIXES):
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        fm = frontmatter(text)
        if not fm:
            continue
        d = (to_date(fm.get("published")) or to_date(fm.get("updated"))
             or to_date(fm.get("created")))
        if not d:
            continue
        slug = rel[:-3] if rel.endswith(".md") else rel
        out.append((d, slug, str(fm.get("type") or "page"), str(fm.get("title") or Path(rel).stem)))
    out.sort(key=lambda x: (x[0], x[1]), reverse=True)
    return out


def render(items: list) -> str:
    L = ["---", "type: dashboard", 'title: "Timeline"',
         f"updated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}", "---", "", "# Timeline", "",
         f"Reverse-chronological view of the vault's dated content "
         f"({len(items)} pages, newest first). Generated by `okengine.timeline`."]
    if not items:
        L += ["", "_No dated pages yet._"]
        return "\n".join(L) + "\n"
    cur_month = None
    for d, slug, typ, title in items[:MAX_ENTRIES]:
        month = d.strftime("%Y-%m")
        if month != cur_month:
            cur_month = month
            L += ["", f"## {month}", ""]
        L.append(f"- {d.isoformat()} · `{typ}` · [[{slug}]] — {title}")
    if len(items) > MAX_ENTRIES:
        L += ["", f"_…{len(items) - MAX_ENTRIES} older pages omitted (max_entries={MAX_ENTRIES})._"]
    return "\n".join(L) + "\n"


def main() -> int:
    items = collect(WIKI)
    DASH_PATH.parent.mkdir(parents=True, exist_ok=True)
    DASH_PATH.write_text(render(items), encoding="utf-8")
    print(f"timeline: {len(items)} dated page(s) -> {DASH_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
